### ISSUE TITLE
Line jumps in Vim

### ISSUE THREAD

**Issue by andys8** [cog1to/st-ligatures#10]
Hey, first of all thanks for this patch. Ligatures were missing a long time in st :)

I was keen to give it a try. I noticed an issue in Vim. If I hold a key to go down or upwards and release it, it sometimes happens that the cursor is jumping to the next line. I went back to the previous st build and couldn't reproduce this issue in this way. I'm not sure how the patch would lead to this issue. I think it could be related to the new redrawing of lines or kind of a performance artifact.

https://github.com/cog1to/st-ligatures/blob/2f37fcaf79ecec0491b7406d681a564cb54b3ac7/st-ligatures-20200406-28ad288.diff#L205-L213

The issue happens only some times. After releasing the key, the cursor jumps to the next line instead of stopping.

![ligatures](https://user-images.githubusercontent.com/13085980/80291647-c07ff980-874f-11ea-944f-72329385d158.gif)

### Info

Vim: 8.2
Build: https://github.com/andys8/st/tree/patch-ligatures-scrollback
(scrollback, boxdraw, and other patches)
File: https://github.com/andys8/vim-emulation/blob/1c58077d5b50ae40a36c0ae55a60f9dedf6af667/tests/TestUtil.elm

**Comment by cog1to** [comment]
I cannot reproduce it so far, but in case it is some kind of weird performance artifact: I'm working on small refactoring to simplify the drawing code in my patch. If you have time, please try building with patches from [br_draw_optimization](https://github.com/cog1to/st-ligatures/tree/br_draw_optimization) branch.

**Comment by andys8** [comment]
The changes in https://github.com/cog1to/st-ligatures/commit/4899868bbc0a9187a698ecfc9850749ada920169 modify the behavior and it looks to me, that the issue is either solved or at least happens less or isn't as obvious anymore.

I will give these updated patches a try and keep my eyes open. Consider the issue solved :) Thanks for your work.
