### ISSUE TITLE
Vim popupmenu

### ISSUE THREAD

**Issue by zacmar** [cog1to/st-ligatures#11]
Popupmenus in vim/neovim are not displayed properly when using this patch.
Examples (patch is applied on the left side):

![ex1](https://user-images.githubusercontent.com/32982619/80385922-000d2980-88a7-11ea-8a6d-034d5391a374.png)
![ex2](https://user-images.githubusercontent.com/32982619/80385924-013e5680-88a7-11ea-82f3-4291d22ff13f.png)
![ex3](https://user-images.githubusercontent.com/32982619/80385926-01d6ed00-88a7-11ea-953e-760d6bfab691.png)

**Comment by cog1to** [comment]
Interestingly, it works fine for me in st from `28ad288` on my color scheme.
![vim-autocomplete-popup](https://user-images.githubusercontent.com/1484965/80408990-c7824580-88d0-11ea-874a-cd641db77f6d.png)

1. What version of st are you testing with?
2. What color scheme/plugin is this?

**Comment by zacmar** [comment]
I experimented a little more. I checked out HEAD and applied the patch manually (the patch doesnt apply on HEAD cleanly). It works just fine. So must be my combination of patches that's causing the issue. I am using [this](https://github.com/LukeSmithxyz/st) distribution of `st` and applied the patch manually.
So to answer your questions directly:
1. I tested it with the above linked version of `st`.
2. That includes `virtcenter`, `scrollback`, `font2`, `xresources` and some other modifications.
3. The screenshots show `coc.nvim` using the `gruvbox` color scheme. I can confirm however that this is irrelevant, since the issue persists when using `nvim -u NORC st.c` and using vims built-in insert completion(`<C-N>`).
4. Yes. The i applied the patch manually. Output when trying to apply the patch:
```
patching file Makefile
patching file config.mk
Hunk #1 FAILED at 15.
1 out of 1 hunk FAILED -- saving rejects to file config.mk.rej
patching file hb.c
patching file hb.h
patching file st.c
Hunk #1 FAILED at 2584.
1 out of 1 hunk FAILED -- saving rejects to file st.c.rej
patching file st.h
patching file x.c
Hunk #1 succeeded at 20 (offset 1 line).
Hunk #2 succeeded at 1132 (offset 100 lines).
Hunk #3 succeeded at 1322 (offset 89 lines).
Hunk #4 succeeded at 1429 (offset 89 lines).
```

**Comment by zacmar** [comment]
Ok, nevermind. I can not reproduce the issue myself anymore. I just cloned https://github.com/LukeSmithxyz/st.git again, downloaded the patch and applied it. It fails, but the conflicts are trivial to sort out by hand (in fact I dont even see the reason why it fails when looking at the diffs and the reject files on first glance). I guess this can be closed, I must have butchered something somewhere myself. Thanks for the help!
