### ISSUE TITLE
patch "st-ligatures-20200428-28ad288.diff" fails on latest st vanilla

### ISSUE THREAD

**Issue by palemoongod** [cog1to/st-ligatures#12]
### i guess the diff file needs to be updated

**git clone https://git.suckless.org/st
cd st
wget https://st.suckless.org/patches/ligatures/st-ligatures-20200428-28ad288.diff
patch < st-ligatures-20200428-28ad288.diff**

patching file Makefile
patching file config.mk
patching file hb.c
patching file hb.h
patching file st.c
Hunk #1 FAILED at 2585.
1 out of 1 hunk FAILED -- saving rejects to file st.c.rej
patching file st.h
patching file win.h
patching file x.c

**Comment by cog1to** [comment]
Added 0.8.3 version in 6eb54433
