### ISSUE TITLE
using features crashes st

### ISSUE THREAD

**Issue by paulhersch** [cog1to/st-ligatures#24]
Hi,

Compiling with ss01 and ss02 added to the features array crashes st instantly with the error:
```
mremap_chunk(): invalid pointer
zsh: abort (core dumped)  st
```
line 30 in hb.c is:
`hb_feature_t features[] = { FEATURE('s', 's', '0', '1'), FEATURE('s', 's', '0', '2') }; `

The features (rendered via harfbuzz) definitely work with the font, i have successfully tested them with wezterm.

is there some error on my end that causes this? I am using Cascadia Code and coding ligatures work perfectly fine for me.

I hope this issue can be resolved somehow!
Thank you for your time

**Comment by cog1to** [comment]
Can't reproduce it easily.

1. Do you use the latest version of the patch?
2. What version of st are you patching?
3. Do you have any other patches applied besides ligatures?
4. Do you have any kind of special prompt set up? Can you test the behavior without it?

**Comment by paulhersch** [comment]
Hi,
1. I am currently using flexipatch ("preprocessed" with a nix module i wrote that just adds the features). Flexipatch currently uses the latest version of your patch as far as i could tell when i checked.
2. current git
3. i use quite a few different patches, will test behaviour with less applied
4. gonna do that as well, will test the default bash prompt

**Comment by paulhersch** [comment]
It seems like it was just a faulty configuration on my end that caused this. Using the default config.h with just Cascadia Code set as font works. Should have thought of trying that out earlier.

Sorry to bother you and thank you for Your time!
