### ISSUE TITLE
Memory corruption

### ISSUE THREAD

**Issue by froloffw7** [cog1to/st-ligatures#29]
Hello,

It seems that I found the bug in your code, which may cause heap memory corruption.
The code presume that every glyph in the output buffer created by the HB transformation correspond to the input unicode char, while this is not correct for the fonts with complex ligatures and other futures.
For example, Fira Code font represent symbol Ǜ (unicode 0x1db) with two glyphs. Some Arabic ligatures may require 4 glyphs. As specbuf size is equal to the number of terminal columns (not big enough),  this may cause memory corruption.
gcc switches -fsanitize=address -fsanitize-recover=address -fsanitize=undefined will immediately show this.
Also this cause wrong symbol position on the screen (extra space). Fortunately, hb library returns symbol index for each glyph in the struct field `cluster`.
Proposed main change is for the xmakeglyphfontspecs() x.c source:

```
			hbtransform(&shaped, font->match, glyphs, start, length);
			runewidth = win.cw * ((glyphs[start].mode & ATTR_WIDE) ? 2.0f : 1.0f);
			for (int code_idx = 0; code_idx < shaped.count; code_idx++) {

				int idx = shaped.glyphs[code_idx].cluster;
				// This should be already processed by the caller 
				// if (glyphs[start + idx].mode & ATTR_WDUMMY)
				//	continue;
				xp = winx + idx * runewidth;

				if (shaped.glyphs[code_idx].codepoint != 0) {
					/* If symbol is found, put it into the specs. */
					specs[numspecs].font = font->match;
					specs[numspecs].glyph = shaped.glyphs[code_idx].codepoint;
					specs[numspecs].x = xp + (short)shaped.positions[code_idx].x_offset;
					specs[numspecs].y = yp + (short)shaped.positions[code_idx].y_offset;
					// xp += runewidth;
					numspecs++;
				} else {
					/* If it's not found, try to fetch it through the font cache. */
					rune = glyphs[start + idx].u;
...
```
specbuf could be fixed size, big enough for any line width, for example 4096 elements.

Also I suggest  to add all symbols in one call in the function hbtransform() hb.c, as it recommended by HB developers:

```
	hb_buffer_set_direction(buffer, HB_DIRECTION_LTR);

	Rune rune[4096];
	const Glyph *glyphs_ptr = &glyphs[start];
	if (length > 4096) length = 4096; // pranoya

	for (i = 0; i < length; i++) {
		if (glyphs_ptr->mode & ATTR_WDUMMY)
			rune[i] = 0x0020;
		else
			rune[i] = glyphs_ptr->u;
		glyphs_ptr++;
	}
	/* Fill buffer with codepoints. */
	hb_buffer_add_codepoints(buffer, rune, length, 0, length);

	/* Shape the segment. */
	hb_shape(font, buffer, features, sizeof(features)/sizeof(hb_feature_t));

```

**Comment by cog1to** [comment]
I don't think your changes would be enough to make it work.

First, the clustering doesn't seem to work unless we explicitly provide cluster values before shaping. By default, it seems, if we use `hb_buffer_add_codepoints`, all cluster values will be set to 0 and will most likely remain 0 after shaping.

The bigger problem is that procedures like `xdrawline` also assume that one cell is matched by one `spec`, and they  would require some updates to break from that assumption.  Ligatures work, because we effectively reduce the number of glyphs, replacing the missing ones with `W_DUMMY` characters, but increasing the glyph sequence is a whole another problem to solve here.

Thanks for the reporting though. I'll try to tinker with the code more to see if there's a good solution for this issue.

**Comment by froloffw7** [comment]
Well, the code above I extracted it from my working st build. And the clusters have the correct values  after `hb_shape()` call, `harfbuzz` version 2.6.4 
`xdrawline` should not depend on the spec symbol matching. 
I can't make the full diff, sorry as I applied several patches before. Below the changed code.

```
void
xdrawline(Line line, int x1, int y1, int x2)
{
	int i, x, ox, numspecs;
	Glyph base, cur;
	XftGlyphFontSpec *specs = xw.specbuf;

	i = 0;
	for (x = x1; x < x2; x++) {
		cur = line[x];
		if (cur.mode == ATTR_WDUMMY)
			continue;
		if (selected(x, y1))
			cur.mode |= ATTR_SELECTED;
		if ((i > 0) && ATTRCMP(base, cur)) {
			numspecs = xmakeglyphfontspecs(specs, &line[ox], x - ox, ox, y1);
			xdrawglyphfontspecs(specs, base, numspecs, ox, y1);
			i = 0;
		}
		if (i == 0) {
			base = cur;
			ox = x;
		}
		i++;
	}
	if (i > 0) {
		numspecs = xmakeglyphfontspecs(specs, &line[ox], x2 - ox, ox, y1);
		xdrawglyphfontspecs(specs, base, numspecs, ox, y1);
	}
}

```

**Comment by cog1to** [comment]
Strange, maybe I messed up something with the clusters.

The `xdrawline` part is crucial though. I see that you've put call to `xmakeglyphfontspecs` inside the loop, this fixes the issue with spec length and line length mismatch.

**Comment by froloffw7** [comment]
The [harfbuzz manual](https://harfbuzz.github.io/harfbuzz-hb-buffer.html#hb-glyph-info-t) doesn't mention any cluster assignment to the zero.

uint32_t cluster | the index of the character in the original text that corresponds to this hb_glyph_info_t, or whatever the client passes to hb_buffer_add(). More than one hb_glyph_info_t can have the same cluster value, if they resulted from the same character (e.g. one to many glyph substitution), and when more than one character gets merged in the same glyph (e.g. many to one glyph substitution) the hb_glyph_info_t will have the smallest cluster value of them. By default some characters are merged into the same cluster (e.g. combining marks have the same cluster as their bases) even if they are separate glyphs...
-- | --

**Comment by cog1to** [comment]
Yeah, I think I just applied a small change on top of yours that was wrong.

There seem to be another small issue with wide character handling (I'm testing it with Chinese/Japanese hieroglyphs), I think it's related to the code you've commented out. When I fix it and test the whole thing a little more, I'll try to compose a new patch version. Stay tuned :)

**Comment by cog1to** [comment]
Ok, I managed to make it work kinda properly in [br-harfbuzz-expand-fix](https://github.com/cog1to/st-ligatures/tree/br-harfbuzz-expand-fix) branch.

But there's still an issue, with, for example Ǜ not rendering properly with Fira Code, because the bar goes above the symbol, and `st` explicitly clips the region to font height when rendering each symbol. 

Because of this, I wonder if it is worth the trouble, or it would be easier just to use first glyph of every cluster and ignore the rest.

**Comment by froloffw7** [comment]
As **st** clip the region, I don't think this should be a problem, so we can keep all glyphs. We can also report the issue to Fira Code author.
I noticed that you add offsets division by 64, does it depends on the font size?

**Comment by cog1to** [comment]
I don't think it's a bug in the font, it's normal for accent symbols to go above the normal font height. It's a problem for st though.

The division by 64 is not font size dependent as far as I know, it is a conversion from font's unit of measurement to pixels. The font size scaling should be already applied by Harfbuzz at this point.
