### ISSUE TITLE
ATTR_WRAP issue in xmakeglyphfontspecs

### ISSUE THREAD

**Issue by veltza** [cog1to/st-ligatures#32]
Hi, and thanks for your ligature patch.

I found an issue in xmakeglyphfontspecs() function that caused glyphs to overlap each other. The problem was that `ATTRCMP()` masked out the `ATTR_WRAP` attribute, but `prevmode != mode` comparison did not:

```C
if (
	prevmode != mode
	|| ATTRCMP(glyphs[start], glyphs[i])
	|| selected(x + i, y) != selected(x + start, y)
	|| i == (len - 1)
) {
```

Because there is another `prevmode != mode` comparison as well, I propose the following fix:

```diff
diff --git a/x.c b/x.c
index 8804a4c..7f53cc2 100644
--- a/x.c
+++ b/x.c
@@ -1279,11 +1279,11 @@ xmakeglyphfontspecs(XftGlyphFontSpec *specs, const Glyph *glyphs, int len, int x
 	HbTransformData shaped = { 0 };
 
 	/* Initial values. */
-	mode = prevmode = glyphs[0].mode;
+	mode = prevmode = glyphs[0].mode & ~ATTR_WRAP;
 	xresetfontsettings(mode, &font, &frcflags);
 
 	for (i = 0, xp = winx, yp = winy + font->ascent; i < len; ++i) {
-		mode = glyphs[i].mode;
+		mode = glyphs[i].mode & ~ATTR_WRAP;
 
 		/* Skip dummy wide-character spacing. */
 		if (mode & ATTR_WDUMMY && i < (len - 1))
```

Could you please check it out? Thanks.

**Comment by cog1to** [comment]
Hi, thanks for the report.

Is there any easy way to reproduce this? Like a specific terminal dimensions and a file or just a text snippet to render?

**Comment by veltza** [comment]
It's very tricky to reproduce, but let's try.

1. Use the vanilla st with st-ligatures-20230105-0.9.diff
2. Use zsh v5.8 or v5.9
3. Change the terminal window width to 34 characters
4. Set a simple prompt `PS1='>'`
5. Paste or type the following command
`echo                          abcdefghijklmnopqrst`
so that the line wrapping occurs after the **abc** characters:
![1](https://github.com/cog1to/st-ligatures/assets/106755522/ab294a8c-68bd-491d-990e-c10794fd6c6f)
7. Move the cursor to the beginning of the **abc** and start pressing backspace until some glyps overlap each other (in here h and i overlap):
![2](https://github.com/cog1to/st-ligatures/assets/106755522/9bab6506-5b6f-4da9-b070-f50f486c4ae3)

Why is this happening? When you press backspace, zsh sends the DCH sequence that triggers the tdeletechar() function:

```C
void
tdeletechar(int n)
{
	int dst, src, size;
	Glyph *line;

	LIMIT(n, 0, term.col - term.c.x);

	dst = term.c.x;
	src = term.c.x + n;
	size = term.col - src;
	line = term.line[term.c.y];

	memmove(&line[dst], &line[src], size * sizeof(Glyph));
	tclearregion(term.col-n, term.c.y, term.col-1, term.c.y);
}
```

And that function doesn't clear the ATTR_WRAP attribute when it deletes and moves characters, so the line now has the extra line wrapping attribute(s) and the ligature patch doesn't like it. I didn't dig deeper into how the patch works, so I don't know why they're causing issues there, but I hope you can shed some light.

Interestingly, this doesn't happen on bash, so it seems to be just a zsh related issue.

**Comment by veltza** [comment]
> To be fair, it seems like a bug in ST logic. The tdeletechar function should properly clean up attributes that are no longer relevant in addition to memcpy-ing the segment. But I see why it was not really affecting anything without ligatures logic.

Yes, you can fix this issue by fixing the tdeletechar() function. But I'm concerned that there might be other edge cases too and therefore the patch should be foolproof and tolerant of bad data.

> Anyway, I've made a PR with the fix. Can you check it out and report back with whether the issue is fixed?

I've been using this fix for a while and haven't had any issues since. Of course, I haven't tested all the patches, but visually they seem to be fine. So I think they are ready for production.

**Comment by cog1to** [comment]
Merged the fix
