### ISSUE TITLE
about https://st.suckless.org/patches/ligatures/

### ISSUE THREAD

**Issue by neuromagus** [cog1to/st-ligatures#38]
If you have a time, please, update info [here](https://st.suckless.org/patches/ligatures/) for 9.2 version...

Most users did not fix ```hunk FAILED```...

**Comment by neuromagus** [comment]
and...

clean st latest from here - https://dl.suckless.org/st/st-0.9.2.tar.gz

this block of code did not patched:
```
 patch -p1 < st-ligatures-scrollback-0.9.2.diff 
patching file Makefile
Hunk #2 succeeded at 16 (offset -6 lines).
patching file config.mk
patching file hb.c
patching file hb.h
patching file st.c
Hunk #1 FAILED at 2711.
1 out of 1 hunk FAILED -- saving rejects to file st.c.rej
patching file st.h
patching file win.h
patching file x.c
Hunk #9 succeeded at 1711 (offset 6 lines).
Hunk #10 succeeded at 1729 (offset 6 lines).

```

st.c.rej

```
--- st.c
+++ st.c
@@ -2711,7 +2711,8 @@ draw(void)
 	drawregion(0, 0, term.col, term.row);
 	if (term.scr == 0)
 		xdrawcursor(cx, term.c.y, term.line[term.c.y][cx],
-				term.ocx, term.ocy, term.line[term.ocy][term.ocx]);
+				term.ocx, term.ocy, term.line[term.ocy][term.ocx],
+				term.line[term.ocy], term.col);
 	term.ocx = cx;
 	term.ocy = term.c.y;
 	xfinishdraw();
```

**Comment by cog1to** [comment]
I already pushed it into their git. The guys running the site are slow to update it for some reason.

**Comment by cog1to** [comment]
As for the patch, seems like you tried to apply the scrollback version instead of the vanilla version. The correct order is to apply the `scrollback` patch first, and then the `ligatures-scrollback` patch on top of it.

**Comment by neuromagus** [comment]
>if you don't want the scrollback patch.

You are right. I apply this patch without ```scrollback```. I think ```scrollback``` included here. 

Thanks a lot.
