### ISSUE TITLE
Does not work together with boxdraw patch

### ISSUE THREAD

**Issue by GAhlekzis** [cog1to/st-ligatures#6]
Hello!
I found your beautiful piece of software just today and immediately wanted to spice up my terminal with it.

But I ran into a problem which I imagine is related to the boxdraw patch I also use. It looks like this:
![st-lig](https://user-images.githubusercontent.com/10133257/78609170-713a5d80-7862-11ea-95db-0aa19894f546.png)
On the left side is st before modification and on the right after applying (and merging) your ligature patch. Both are running tmux which is the cause of the top line and also a good way to make sure both terminals are displaying the same thing.

Anyway to give you the full picture I uploaded the source I'm working off to my git server with all the applied patches.
To be found here: [Repository](https://git.aljordan.dev/alj/st)

I would appreciate so much if this issue would be resolved, as I spent hours today trying to troubleshoot and fix this myself albeit having no experience with neither fonts nor programming in C, but the part of it I got working was so beautiful that it was still worth to try.

I'm probably a bit rambly by now, as it is past midnight for me, so I apologize and wish you the greatest of days. 
- Alex

**Comment by cog1to** [comment]
Please check the patch in `br_boxdraw_compatibility` branch. If everything is ok, I'll merge the PR.
